version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: finplatform-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./finplatform.db:/app/finplatform.db
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: finplatform-db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: finplatform-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped